sudo: required #super user permisions needed
services:
 - docker

before_install:
 - docker build -t ciiru/ecommerce -f Dockerfile.dev . #build new container with tag

script:
 - docker run ciiru/ecommerce npm run test -- -- coverage #overide the defautl command and exit when test has run 
